App\Entity\Client:
  collectionOperations:
    get:
      security: 'is_granted("ROLE_USER")'
    post: ~
  itemOperations:
    get: ~
    put: ~
    delete: ~

App\Entity\Notification:
  collectionOperations:
    get:
      security: 'is_granted("ROLE_USER")'
      filters: [ 'notification.order_filter', 'notification.search_filter' ]
    post:
      security: 'is_granted("ROLE_USER")'
      method: "POST"
      input: "App\\Dto\\NotificationMultipleRequest"
      controller: "App\\Controller\\Notification\\CreateMultipleAction"
      openapi_context:
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      $ref: "#/components/schemas/Notification"
  itemOperations:
    get:
      security: 'is_granted("ROLE_USER")'