framework:
  messenger:
#    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 3
          multiplier: 2

    routing:
      'App\Service\Message\NotificationMessage': async

#  when@test:
#    framework:
#      messenger:
#        transports:
#          # replace with your transport name here (e.g., my_transport: 'in-memory://')
#          # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#          async: 'in-memory://'